sudo: required
language: generic
dist: trusty

cache:
    directories:
        - "~/.platformio"
install:
  - ./install.sh

script:
  - particle compile photon particle/firmware/
  - cd nano && platformio run
